import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Charts generated by viz.chart — the SVG is stored here and served via
 * /api/charts/[id], so an agent (or chat) gets back a short, stable URL it can
 * embed, instead of a huge data-URL it would have to copy verbatim.
 */
export const charts = pgTable("charts", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title"),
  svg: text("svg").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
