import { jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Charts generated by viz.chart — served via /api/charts/[id]. `svg` is the
 * static render (image embed + PDF); `spec` is the chart spec so the chat can
 * render the SAME chart INTERACTIVELY client-side (hover/zoom/pan).
 */
export const charts = pgTable("charts", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title"),
  svg: text("svg").notNull(),
  spec: jsonb("spec"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
